### PR TITLE
Symfony: Updated framework version and codebase to match best practices

### PR DESCRIPTION
**Pull request by aminemat**
The Symfony app was a bit outdated so I made those changes:

- Upgraded Symfony version to 2.7.
- Grouped NoteBundle and UserBundle inside AppBundle.
- Moved Route declarations to controllers.
- Moved translation files to app/resources.
- Moved service declarations to app/services.yml.
- Moved submit buttons from form classes into views.
- Replaced the deprecated setDefaultOptions() calls by configureOptions()
- Added docblocks and typehints where needed.

### CODE REVIEW

**Comment by komarserjio** [comment]
Hey @aminemat. Curios what is the pros of merging NoteBundle and UserBundle?

**Comment by aminemat** [comment]
@komarserjio that's a best practice from Symfony: http://symfony.com/doc/current/best_practices/business-logic.html
All the recent docs and resources use a single AppBundle.

**Comment by komarserjio** [comment]
@aminemat, tests are passing on your machine?

**Comment by aminemat** [comment]
yep 

> PHPUnit 4.2.6 by Sebastian Bergmann.
Time: 1.61 seconds, Memory: 44.25Mb
OK (15 tests, 8 assertions)

**Comment by komarserjio** [comment]
This is awesome update :)

**Comment by aminemat** [comment]
Thanks for merging it so quickly !

**Comment by komarserjio** [comment]
It's really hard for me to keep all apps up to date, so I really appreciate help like this.
I'm looking for enthusiasts who could help to drive the project and maintain some frameworks (or maybe even language). Looks like you are passionated about the Symfony and it would be great to have maintainer like you.

Let me know if it is interesting to you :)

**Comment by aminemat** [comment]
sure thing

**Comment by komarserjio** [comment]
Great :)
I will make a note in symfony's README that you are maintainer.

**Comment by aminemat** [comment]
great, thanks !

**Pull request merged**
